# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price_for_day', models.FloatField()),
                ('car_class', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')])),
                ('is_rent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarRents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('price_sum', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_nr', models.CharField(max_length=50)),
                ('flat_nr', models.CharField(max_length=50, null=True)),
                ('rents', models.ManyToManyField(through='rentcar_app.CarRents', to='rentcar_app.Car')),
            ],
        ),
        migrations.AddField(
            model_name='carrents',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentcar_app.Customer'),
        ),
    ]
