# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='flat_nr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
