# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-22 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar_app', '0002_auto_20180421_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
