# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-22 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentcar_app', '0003_car_car_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='rents',
        ),
        migrations.AddField(
            model_name='car',
            name='rents',
            field=models.ManyToManyField(through='rentcar_app.CarRents', to='rentcar_app.Customer'),
        ),
    ]
